
services:
  tgbot:
    container_name: tgbot
    build: .
    env_file: 
      - ./.env
    restart: unless-stopped

  db:
    container_name: mindfull_db
    image: postgres:15.1-bullseye
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - TZ=Europe/Kiev
    env_file:
      - ./.env
    ports:
      - 5432:5432
    restart: unless-stopped
